/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.probestack.forgestudio.design.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-23T10:25:40.019199831Z[GMT]")@Validated
@Tag(name = "MockRuntime", description = "the MockRuntime API")
public interface MockRuntimeApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /mock/{mockUrl}/{path} : Handle incoming DELETE request to mock server
     *
     * @param mockUrl  (required)
     * @param path  (required)
     * @return Mocked response returned (status code 200)
     */
    @Operation(
        operationId = "mockMockUrlPathDelete",
        summary = "Handle incoming DELETE request to mock server",
        tags = { "MockRuntime" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Mocked response returned")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/mock/{mockUrl}/{path}"
    )
    
    default ResponseEntity<Void> mockMockUrlPathDelete(
        @Parameter(name = "mockUrl", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mockUrl") String mockUrl,
        @Parameter(name = "path", description = "", required = true, in = ParameterIn.PATH) @PathVariable("path") String path
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }


    /**
     * GET /mock/{mockUrl}/{path} : Handle incoming GET request to mock server
     *
     * @param mockUrl  (required)
     * @param path  (required)
     * @return Mocked response returned (status code 200)
     */
    @Operation(
        operationId = "mockMockUrlPathGet",
        summary = "Handle incoming GET request to mock server",
        tags = { "MockRuntime" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Mocked response returned")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/mock/{mockUrl}/{path}"
    )
    
    default ResponseEntity<Void> mockMockUrlPathGet(
        @Parameter(name = "mockUrl", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mockUrl") String mockUrl,
        @Parameter(name = "path", description = "", required = true, in = ParameterIn.PATH) @PathVariable("path") String path
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }


    /**
     * POST /mock/{mockUrl}/{path} : Handle incoming POST request to mock server
     *
     * @param mockUrl  (required)
     * @param path  (required)
     * @return Mocked response returned (status code 200)
     */
    @Operation(
        operationId = "mockMockUrlPathPost",
        summary = "Handle incoming POST request to mock server",
        tags = { "MockRuntime" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Mocked response returned")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/mock/{mockUrl}/{path}"
    )
    
    default ResponseEntity<Void> mockMockUrlPathPost(
        @Parameter(name = "mockUrl", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mockUrl") String mockUrl,
        @Parameter(name = "path", description = "", required = true, in = ParameterIn.PATH) @PathVariable("path") String path
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }


    /**
     * PUT /mock/{mockUrl}/{path} : Handle incoming PUT request to mock server
     *
     * @param mockUrl  (required)
     * @param path  (required)
     * @return Mocked response returned (status code 200)
     */
    @Operation(
        operationId = "mockMockUrlPathPut",
        summary = "Handle incoming PUT request to mock server",
        tags = { "MockRuntime" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Mocked response returned")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/mock/{mockUrl}/{path}"
    )
    
    default ResponseEntity<Void> mockMockUrlPathPut(
        @Parameter(name = "mockUrl", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mockUrl") String mockUrl,
        @Parameter(name = "path", description = "", required = true, in = ParameterIn.PATH) @PathVariable("path") String path
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }

}
