/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.probestack.forgestudio.design.api;

import com.probestack.forgestudio.design.model.CreateMockRequest;
import com.probestack.forgestudio.design.model.MockResponse;
import java.util.UUID;
import com.probestack.forgestudio.design.model.UpdateMockRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-23T11:06:32.467428401Z[GMT]")@Validated
@Tag(name = "MockServers", description = "the MockServers API")
public interface MockServersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /mocks/{mockId} : Delete mock server
     *
     * @param mockId  (required)
     * @return Mock server deleted successfully (status code 204)
     */
    @Operation(
        operationId = "mocksMockIdDelete",
        summary = "Delete mock server",
        tags = { "MockServers" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Mock server deleted successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/mocks/{mockId}"
    )
    
    default ResponseEntity<Void> mocksMockIdDelete(
        @Parameter(name = "mockId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mockId") UUID mockId
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }


    /**
     * GET /mocks/{mockId} : Get mock server by ID
     *
     * @param mockId  (required)
     * @return Mock server details (status code 200)
     */
    @Operation(
        operationId = "mocksMockIdGet",
        summary = "Get mock server by ID",
        tags = { "MockServers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Mock server details", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MockResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/mocks/{mockId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<MockResponse> mocksMockIdGet(
        @Parameter(name = "mockId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mockId") UUID mockId
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "{ \"delayMs\" : 0, \"requestCount\" : 6, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"mockUrl\" : \"mockUrl\", \"name\" : \"name\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"isPrivate\" : true, \"collectionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"workspaceId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }


    /**
     * PUT /mocks/{mockId} : Update mock server configuration
     *
     * @param mockId  (required)
     * @param updateMockRequest  (required)
     * @return Mock server updated successfully (status code 200)
     */
    @Operation(
        operationId = "mocksMockIdPut",
        summary = "Update mock server configuration",
        tags = { "MockServers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Mock server updated successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/mocks/{mockId}",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> mocksMockIdPut(
        @Parameter(name = "mockId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mockId") UUID mockId,
        @Parameter(name = "UpdateMockRequest", description = "", required = true) @Valid @RequestBody UpdateMockRequest updateMockRequest
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }


    /**
     * PATCH /mocks/{mockId}/toggle : Enable or disable mock server (private/public control)
     *
     * @param mockId  (required)
     * @return Mock server state updated successfully (status code 200)
     */
    @Operation(
        operationId = "mocksMockIdTogglePatch",
        summary = "Enable or disable mock server (private/public control)",
        tags = { "MockServers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Mock server state updated successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/mocks/{mockId}/toggle"
    )
    
    default ResponseEntity<Void> mocksMockIdTogglePatch(
        @Parameter(name = "mockId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("mockId") UUID mockId
    ) {
                        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                    }


    /**
     * GET /workspaces/{workspaceId}/mocks : Get all mock servers in a workspace
     *
     * @param workspaceId  (required)
     * @return List of mock servers (status code 200)
     */
    @Operation(
        operationId = "workspacesWorkspaceIdMocksGet",
        summary = "Get all mock servers in a workspace",
        tags = { "MockServers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of mock servers", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = MockResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/workspaces/{workspaceId}/mocks",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<MockResponse>> workspacesWorkspaceIdMocksGet(
        @Parameter(name = "workspaceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("workspaceId") UUID workspaceId
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "[ { \"delayMs\" : 0, \"requestCount\" : 6, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"mockUrl\" : \"mockUrl\", \"name\" : \"name\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"isPrivate\" : true, \"collectionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"workspaceId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"delayMs\" : 0, \"requestCount\" : 6, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"mockUrl\" : \"mockUrl\", \"name\" : \"name\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"isPrivate\" : true, \"collectionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"workspaceId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ]";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }


    /**
     * POST /workspaces/{workspaceId}/mocks : Create a mock server inside a workspace
     *
     * @param workspaceId  (required)
     * @param createMockRequest  (required)
     * @return Mock server created successfully (status code 201)
     */
    @Operation(
        operationId = "workspacesWorkspaceIdMocksPost",
        summary = "Create a mock server inside a workspace",
        tags = { "MockServers" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Mock server created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MockResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/workspaces/{workspaceId}/mocks",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<MockResponse> workspacesWorkspaceIdMocksPost(
        @Parameter(name = "workspaceId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("workspaceId") UUID workspaceId,
        @Parameter(name = "CreateMockRequest", description = "", required = true) @Valid @RequestBody CreateMockRequest createMockRequest
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "{ \"delayMs\" : 0, \"requestCount\" : 6, \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"mockUrl\" : \"mockUrl\", \"name\" : \"name\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"isPrivate\" : true, \"collectionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"workspaceId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }

}
